### ISSUE TITLE
想問下，這個項目是否支持創建群組？

### ISSUE THREAD

**Issue by qiumingben** [UncleCatMySelf/InChat#9]
想問下，這個項目是否支持創建群組？

**Comment by UncleCatMySelf** [comment]
暂时还不支持哦，目前的考虑是由核心业务框架进行【添加好友】、【组建群聊】等业务，然后每个用户登录的时候**InChat**也会同步登录，你只需要将通讯的信息传给InChat的群聊、单聊接口就好，它会帮你传输，1.3版之后可能要等到功能稳定，才会添加更多模块业务。我会记录这个需求的，谢谢您的提问。
